spring:
  jpa:
    open-in-view: false
    generate-ddl: true # Whether to initialize the schema on startup.
    hibernate.ddl-auto: create-drop
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/appDB
    username: username
    password: password
    driver-class-name: org.postgresql.Driver